# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.3
language: swift
cache: cocoapods
podfile: Example/Podfile
xcode_workspace: SwiftDog.xcworkspace
xcode_scheme: SwiftDog-Example
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
- pod install --project-directory=Example
script:
- xctool -workspace Example/SwiftDog.xcworkspace -scheme SwiftDog-Example build test
after_script:
- pod lib lint
